name: {{ cookiecutter.strategy_name }}

plugins:
  - name: solidity
  - name: vyper
  - name: hardhat
  - name: alchemy
  - name: etherscan

default_ecosystem: ethereum
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.7.3

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.7.3"

ethereum:
  default_network: mainnet-fork

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy

#test:
