name: {{ cookiecutter.strategy_name }}

plugins:
  - name: solidity
  - name: vyper
  - name: hardhat
  - name: alchemy
  - name: etherscan

default_ecosystem: ethereum
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.7.3
  # TODO: Use https://github.com/jmonteer/yearn-vaults-v3 when tag available
  - name: bufander
    github: bufander/yearn-vaults-v3
    version: 0.0.3

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.7.3"
    # TODO: Use https://github.com/jmonteer/yearn-vaults-v3 when tag available
    - "@yearnvaultsv3=bufander/v0.0.3"

ethereum:
  default_network: mainnet-fork
#  mainnet-fork:
#    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy

#test: